site_name: Bris' Diary for Miss Ana
site_url: https://bris00.github.io/DFMA
site_dir: _site
docs_dir: .

theme:
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
    permalink: true

plugins:
  - search
  - roamlinks

